### ISSUE TITLE
esm_raf not present?

### ISSUE THREAD

**Issue by Supervegito16** [sjevelazco/flexsdm#326]
Hi there,
    I am trying to use flexsdm for modelling my interest species. I noticed there is no `esm_raf` function available.
Please correct me if I am wrong and point me to the relevant function.

Also
the `fit_max` and `esm_max` functions give out results like the rest of the models but the plot output of maxent shows just one number instead of a predictive index like the rest of the models eg. 0.6345 insetad of lets say 1 - 100 range.

Cheers

**Comment by sjevelazco** [comment]
Hi 
There is no function to fit ESM for random forest because it tends to perform less than conventional random forest. See 
* Breiner, F.T., Guisan, A., Bergamini, A., Nobis, M.P., 2015. Overcoming limitations of modelling rare species by using ensembles of small models. Methods in Ecology and Evolution 6, 1210–1218. https://doi.org/10.1111/2041-210X.12403
* Breiner, F.T., Nobis, M.P., Bergamini, A., Guisan, A., 2018. Optimizing ensembles of small models for predicting the distribution of species with few occurrences. Methods Ecol Evol 9, 802–808. https://doi.org/10.1111/2041-210X.12957

You can use fit_raf or tune_raf. 

Regarding your question, "Also the fit_max and esm_max functions give out results like the rest of the models but the plot output of maxent shows just one number instead of a predictive index like the rest of the models eg. 0.6345 insetad of lets say 1 - 100 range." Which kind of plot and function for plotting do you reference? Suitability values in flexsdm range between 0 and 1

Best

**Comment by Supervegito16** [comment]
Hi Santiago

Thank you for the references and clear answer to RAF problem. As for the second question, I am attaching an image output of the same. Maybe this will be more clear as to the problem I am facing. 
![Rplot](https://user-images.githubusercontent.com/106014170/224601791-e7ba1a16-a5b1-4c30-8bde-3c0701a5be09.jpeg)

**Comment by sjevelazco** [comment]
Hi, sorry for my delayed reply. The problem is in the function used to predict maxent. I'll work on it and tell you when it is fixed. Thanks for reporting this error.

**Comment by sjevelazco** [comment]
Hi again, I checked the function, and it works well.  I guess the problem is in your data. Remember that for using maxent (in any family function fit_ tune_ or esm_), you must provide a dataset of presences (or presence-absence) AND background points. In case you use a data frame with presences-absences function will fit a model with presences and background points but will evaluate it with presences-absences. This turns the model more comparable with other algorithms that use presences-absences. 

Below you will find an example to test. In case the problem persists, please, prepare a dataset and send it to me so that I can reproduce your error.

Best

```
?sdm_predict()
equire(dplyr)
require(terra)

data("spp")
somevar <- system.file("external/somevar.tif", package = "flexsdm")
somevar <- terra::rast(somevar)

# Presences absences data
some_sp <- spp %>%
  filter(species == "sp3")
table(some_sp$pr_ab) #12 presences
?sample_background()
# Background points
bg <- sample_background(
  data = some_sp,
  x = "x",
  y = "y",
  n = 1000,
  method = "random",
  rlayer = somevar,
  sp_name = "sp1"
)


some_sp <-
  sdm_extract(
    data = some_sp,
    x = "x",
    y = "y",
    env_layer = somevar
  ) %>%  
  part_random(
    data = .,
    pr_ab = "pr_ab",
    method = c(method = "rep_kfold", folds = 5, replicates = 5)
  )
  
bg <- sdm_extract(
  data = bg,
  x = "x",
  y = "y",
  env_layer = somevar
) %>%  
  part_random(
    data = .,
    pr_ab = "pr_ab",
    method = c(method = "rep_kfold", folds = 5, replicates = 5)
  )

## %######################################################%##
#                                                          #
####          model prediction           ####
#                                                          #
## %######################################################%##
# Fit some models
mglm <- esm_max(
  data = some_sp,
  response = "pr_ab",
  predictors = c("CFP_1", "CFP_2", "CFP_3", "CFP_4"),
  partition = ".part", background = bg
)

ind_p <- sdm_predict(
  models = mglm,
  pred = somevar,
  thr = "max_fpb",
  con_thr = FALSE,
  predict_area = NULL, clamp = FALSE
)
plot(ind_p[[1]])

```

**Comment by Supervegito16** [comment]
Hi Santiago,
        The above code works with the example data but not with mine. I have sent you a reprex for your reference. Please let me know of the road ahead.

 Cheers.
