### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by gortegasolis** [sjevelazco/flexsdm#382]
Hi,
I am getting this error when trying to install from github:
** byte-compile and prepare package for lazy loading
double free or corruption (!prev)
Aborted (core dumped)

My system is:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          4.1                         
year           2024                        
month          06                          
day            14                          
svn rev        86737                       
language       R                           
version.string R version 4.4.1 (2024-06-14)
nickname       Race for Your Life 

It works on R 4.3 within a conda environment.

Kind regards

**Comment by sjevelazco** [comment]
Thabk you for reporting this problem.
Ignacio, can you help to figure out this issue?

Thanks

Santi

**Comment by iminoli-dev** [comment]
Hi gortegasolis,

I see you are using Arch o an Arch-derived OS. I know that an Arch user must configure many things to make dependencies interactions work together.

That looks like a problem with a system library. The problem is likely an issue with one of its many dependencies, but somehow there is no detail about the missing dependencies. 

I'd try 
1st - update.packages(ask=FALSE, checkBuilt=TRUE) to make sure the dependencies are up to date.
2nd - remotes::install_github("sjevelazco/flexsdm@HEAD")

On Linux derived from Debian, you use to have a detail warning of the missing dependency. If these previous steps won't work, you should track this issue down.

Let me know if this works!
IM

**Comment by gortegasolis** [comment]
Hi Ignacio,

Same error after updating packages.

The OS is Ubuntu 22.04. 

Normally, I use precompiled packages from this PPA: deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main (you can find info about the PPA here: https://github.com/eddelbuettel/r2u).

The update.packages(ask=FALSE, checkBuilt=TRUE) did update some packages, so the PPA was lagging behind a bit (it is generally  up to date). However, the problem with flexsdm persists.

I can install flexsdm on the same computer in a conda environment using R4.3.

Other packages can be installed from GitHub without problems.

Kind regards

**Comment by iminoli-dev** [comment]
Hi gortegasolis,

I have installed Linux Mint based on Ubuntu 22.04 and was able to install _flexsdm_ without problems, but it was without using conda. I am not an expert conda user, but in my opinion generally is not the best idea to use conda for R environments (if this can be avoided). The R packages are not well up to date in conda (therefore there may be errors due to the dependencies), which means installing R packages often force you to downgrade the used-installed version of R.

I assume that you have updated the conda environment for R 4.4. I think the problem is definitely in there. The problems of the condas environments are very specific to each PC and therefore difficult to solve without trying many alternatives. Maybe applying some commands of this post [https://medium.com/@tortuecookie/using-r-with-conda-80953395bfe6](https://medium.com/@tortuecookie/using-r-with-conda-80953395bfe6) could get us closer to detecting the problem in your conda environment for R 4.4.

Another possible exploration of the dependency problem (within conda environment R 4.4) is to explore with the pkgdepends package the needs of flexsdm:

install.packages("pkgdepends", dep = T)
library(pkgdepends)
pd <- new_pkg_deps("github::sjevelazco/flexsdm@HEAD")
pd$solve()
pd$draw()

Then, with that result you might see or compare in the conda environment R 4.4 what would be missing to install or update. Please, let me know if you have made any progress in finding a solution to this problem.

IM

**Comment by gortegasolis** [comment]
Hi Ignacio,

Sorry if I got you confused. As I said before:

R 4.4 installed normally from PPA = flexsdm is not installing.

R 4.3 installed within a conda environment = flexsdm installed without problems.

I am comparing the output of pkgdepends with my R 4.4 (base environment) and apparently I have all the right dependencies.

The error comes when compiling flexsdm during the installation. All the dependencies (if any were missing) can be installed without problems.

I just tried to force the installation on another computer with Ubuntu 22.04, and the same error happened. Again it is R 4.4 and it has a previous version of flexsdm working.

Saludos

**Comment by iminoli-dev** [comment]
gortegasolis,

I think I understand the problem a little better now. The error is when trying to install the flexsdm package using the deb PPA [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main. Isn't it?

Looking in detail this PPA deb [arch=amd64] https://r2u.stat.illinois.edu/ubuntu jammy main reports that it only has ~ 23183 CRAN packages and 421 BioConductor packages. Therefore, it does not contain packages from github (where the flexsdm package is hosted).

Additionally, in this link you can see all the R packages contained in .deb format by that PPA [https://r2u.stat.illinois.edu/ubuntu/pool/dists/jammy/main/](https://r2u.stat.illinois.edu/ubuntu/pool/dists/jammy/main/), and flexsdm is not listed there.

I think this is could be the reason why flexsdm cannot be installed in R 4.4 from the PPA (because it is not present in the PPA), but it does work in R 4.3 within a conda environment.

Please let me know if I understand you correctly and what you think, so that I can provide you with further assistance.

IM

**Comment by gortegasolis** [comment]
Hi Ignacio,

No, you are not understanding. Sorry, I will try to make it clear here: 

R 4.3 installed within a conda environment = remotes::install_github("sjevelazco/flexsdm@HEAD") WORKS!!!!!

R 4.4 installed normally from PPA = remotes::install_github("sjevelazco/flexsdm@HEAD") NOT WORKING

Another computer with Ubuntu, R 4.4 and an old installation of flexsdm = remotes::install_github("sjevelazco/flexsdm@HEAD", force = T) NOT WORKING

If I have time, I will create a virtual machine with Ubuntu 22.04 and R 4.4 to try the remotes::install_github("sjevelazco/flexsdm@HEAD") command. However, my guess is that it won't work. I'll let you know.

**Comment by gortegasolis** [comment]
Hi!
I was able to install the package. Failed many times, but then I attempted to install flexsdm before having terra or almost any other package installed and it worked.

Since I normally use precompiled R packages from a PPA, I think there is a conflict between some of such packages and flexsdm, even though the versions of the dependences installed with flexsdm are the same as the packages in the PPA.

I'll leave my answer here in case somebody else has a similar problem. However, the issue is too specific, so I really think it is not in your hands.

GO
